str = input()
str = str.replace('c=','@')
str = str.replace('c-','@')
str = str.replace('dz=','@')
str = str.replace('d-','@')
str = str.replace('lj','@')
str = str.replace('nj','@')
str = str.replace('s=','@')
str = str.replace('z=','@')
print(len(str))