SELECT 
    TITLE,
    UB.BOARD_ID,
    REPLY_ID,
    UR.WRITER_ID,
    UR.CONTENTS,
    TO_CHAR(UR.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD UB JOIN USED_GOODS_REPLY UR ON 
    UB.BOARD_ID = UR.BOARD_ID
WHERE TO_CHAR(UB.CREATED_DATE, 'YYYY') = 2022 AND TO_CHAR(UB.CREATED_DATE, 'MM') = 10
ORDER BY UR.CREATED_DATE, TITLE