SELECT 
    TITLE,
    UB.BOARD_ID,
    REPLY_ID,
    UR.WRITER_ID,
    UR.CONTENTS,
    DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD UB JOIN USED_GOODS_REPLY UR ON 
    UB.BOARD_ID = UR.BOARD_ID
WHERE YEAR(UB.CREATED_DATE) = 2022 AND MONTH(UB.CREATED_DATE) = 10
ORDER BY UR.CREATED_DATE, TITLE